### ISSUE TITLE
Issues with Illustrator Exports

### ISSUE THREAD

**Issue by jkosoy** [billautomata/svg2d3#1]
Awesome tool! I was just playing around with it using an SVG I generated from Adobe Illustrator.

I saw two problems.
1. Looks like having the XML doctype and/or comments in the file caused the utility to fail. That seems pretty minor though, it's easy to take that stuff out and try again.
2. Once that stuff is removed, I get a namespace error.

```
Uncaught NamespaceError: Failed to execute 'setAttributeNS' on 'Element': 'http://www.w3.org/2000/xmlns/' is an invalid namespace for attributes.
```

SVG file can be found here: http://a.rbtry.co/3M2E14230z3p

**Comment by billautomata** [comment]
@jkosoy it was this attr `xmlns:xlink="http://www.w3.org/1999/xlink"` in the svg.

I'm going to blacklist adding that attribute thanks!
